### ISSUE TITLE
Suggestion: code changes to improve Linux compatibility

### ISSUE THREAD

**Issue by isatsam** [SurDno/P2ModLoader#3]
As of 0.0.9, the code is fairly Windows-oriented, which unfortunately makes the tool only semi-functional on Linux and other *nix OSs. These OSs could theoretically use it through Wine compatibility layer, so some changes (mainly in various helpers) could improve the user experience:
## FindSteam() in InstallationLocator.cs
This helper can check for common Steam locatiThis helper can check for common Steam locations on Linux. When ran through Wine, P2ML will, in almost all cases (except for unusual user setups), be able to access the native Linux filesystem through virtual Z:/ drive, and is guaranteed to have sufficient permissions for any file writing/modifying/etc. in /home/$user directory (aka Z:/home/$user to Wine). ons on Linux. When ran through Wine, P2ML will, in almost all cases (except for unusual user setups), be able to access the native Linux filesystem through virtual Z:/ drive, and is guaranteed to have sufficient permissions for any file writing/modifying/etc. in /home/$user directory (aka Z:/home/$user to Wine). 

I've already implemented this over in my [detectlinux branch](https://github.com/isatsam/P2ModLoader/tree/detectlinux), and my personal build of P2ML picks up Steam installation of Patho2 by just a click on "Locate".
## LaunchSteam() in GameLauncher()
This helper could also use the Linux Steam dir + the guaranteed to be present steam.sh launch script instead of steam.exe, which is what I'll probably look into next. As for now, "Launch Steam" crashes the launcher. 

"Launch exe" does work fine, but loses any possible launch options that the user might've set up through Steam (in the properties of the game). Since devices like Steam Deck and laptops could especially use the graphical tweaks* from launch options, it would still be nice to have "Launch Steam" button working as well.

(To give context, we have an example of launch options on [pathomodding wiki](https://pathomodding.miraheze.org/wiki/Tutorial:Performance_improvement_settings_for_Pathologic_2#On_Steam_Deck_/_Linux): using gamemode utility to make the game run on lower resolution, then upscale using FSR. This setting makes Patho2 run on 20-30fps without other optimisations on my laptop with an iGPU, as opposed to powerpoint fps without it...)

## Automatic testing?
To save up a bit of time and trouble for maintainers who only use Windows, a Github Action could be set up to do basic testing of the app against Wine. I'm not sure how to properly test real use cases here, since we can't install Patho2 on a github action worker, but we could at least verify that the latest builds still launch on Wine.

---
As for now all of my work on this issue remains in the [detectlinux branch](https://github.com/isatsam/P2ModLoader/tree/detectlinux) of my fork. Unless this seems like too much trouble to maintain for SurDno, I'd like to continue working on the suggested changes, and will be opening relevant PRs in the future.

**Comment by SurDno** [comment]
Thanks for the input. As this is a Windows Forms application I did not expect to care about supporting other OS, but if it can be launched through Wine, I suppose it wouldn’t hurt to apply the fixes you provided. I do not have a Linux machine so the only way for me to know the app is working would be automated testing, yes.

As I mentioned in your other pull request, please ensure your commits do not alter the existing code style before submitting a pull request.

**Comment by SurDno** [comment]
Implemented as a part of #6.

**Comment by SurDno** [comment]
Included in 0.0.12.
